package com.kioku.api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * Base for content that replicates to clients.
 *
 * <p>Every syncable row carries the same six columns. See
 * {@code docs/sync-contract.md}; in short, {@code updatedAt} decides conflicts,
 * {@code deletedAt} is a tombstone rather than a real delete, and
 * {@code serverSeq} is the cursor clients pull against.
 *
 * <p>Ids are generated by the client, not the database, so a client can create
 * content offline and keep the same identity once it syncs.
 */
@MappedSuperclass
public abstract class SyncableEntity {

    @Id
    @Column(nullable = false, updatable = false)
    private UUID id;

    /** Owner. Every query is scoped by this. */
    @Column(name = "user_id", nullable = false)
    private UUID userId;

    /** Client clock. Informational. */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /** Client clock. The last-write-wins key. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Tombstone. Null means the row is alive. */
    @Column(name = "deleted_at")
    private Instant deletedAt;

    /** Server-assigned, monotonic per user. The pull cursor. */
    @Column(name = "server_seq", nullable = false)
    private long serverSeq;

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public UUID getUserId() { return userId; }
    public void setUserId(UUID userId) { this.userId = userId; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

    public Instant getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Instant updatedAt) { this.updatedAt = updatedAt; }

    public Instant getDeletedAt() { return deletedAt; }
    public void setDeletedAt(Instant deletedAt) { this.deletedAt = deletedAt; }

    public long getServerSeq() { return serverSeq; }
    public void setServerSeq(long serverSeq) { this.serverSeq = serverSeq; }

    /** Whether this row is tombstoned. */
    public boolean isDeleted() { return deletedAt != null; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SyncableEntity other = (SyncableEntity) o;
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return id != null ? Objects.hash(id) : super.hashCode();
    }
}
