-- Kioku server schema.
--
-- Hand-maintained and authoritative. Hibernate runs with ddl-auto: validate,
-- so it checks the entities against this file rather than generating anything.
-- If an entity and this file disagree, the application refuses to start.
--
-- Re-run safe: every statement is IF NOT EXISTS, and Spring runs this on each
-- startup (spring.sql.init.mode: always).
--
-- Sync model is defined in docs/sync-contract.md. In short: ids are UUIDs
-- generated by clients, syncable rows carry updated_at (last-write-wins key),
-- deleted_at (tombstone) and server_seq (pull cursor).

-- ============================================================
-- Accounts
-- ============================================================
-- Server-authoritative. Not synced: there is no offline edit path for account
-- data, so these rows carry no server_seq.

CREATE TABLE IF NOT EXISTS users (
    id                          uuid         PRIMARY KEY,
    email                       varchar(255) NOT NULL,
    email_verified              boolean      NOT NULL DEFAULT false,
    email_verification_token    varchar(255),
    email_verification_sent_at  timestamptz,
    pending_email               varchar(255),
    pending_email_token         varchar(255),
    pending_email_sent_at       timestamptz,
    password_hash               varchar(60)  NOT NULL,
    password_reset_token        varchar(255),
    password_reset_sent_at      timestamptz,
    status                      varchar(20)  NOT NULL DEFAULT 'ACTIVE',
    failed_login_attempts       integer      NOT NULL DEFAULT 0,
    locked_until                timestamptz,
    last_login_at               timestamptz,
    created_at                  timestamptz  NOT NULL,
    updated_at                  timestamptz  NOT NULL,
    deleted_at                  timestamptz,
    version                     bigint
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users (email);
CREATE INDEX IF NOT EXISTS ix_users_email_verification_token ON users (email_verification_token);
CREATE INDEX IF NOT EXISTS ix_users_password_reset_token ON users (password_reset_token);

-- Per-user sequence counter backing server_seq.
--
-- Kept as its own row so assignment can take a row lock. See the sequence
-- assignment section of docs/sync-contract.md: handing out a high-water mark
-- past an in-flight transaction silently loses changes, so the counter must
-- advance under a lock rather than from a shared sequence.
CREATE TABLE IF NOT EXISTS user_sync_state (
    user_id     uuid   PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    current_seq bigint NOT NULL DEFAULT 0
);

-- ============================================================
-- Decks
-- ============================================================

CREATE TABLE IF NOT EXISTS decks (
    id            uuid         PRIMARY KEY,
    user_id       uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name          varchar(255) NOT NULL,
    description   varchar(1000) NOT NULL DEFAULT '',
    shuffle_cards boolean      NOT NULL DEFAULT false,
    is_favorite   boolean      NOT NULL DEFAULT false,
    created_at    timestamptz  NOT NULL,
    updated_at    timestamptz  NOT NULL,
    deleted_at    timestamptz,
    server_seq    bigint       NOT NULL
);

-- Pull queries are always "my rows, changed since N", so user_id leads.
CREATE INDEX IF NOT EXISTS ix_decks_sync ON decks (user_id, server_seq);

-- Deck names are unique per user among live decks. Tombstones are excluded so
-- a name frees up once its deck is deleted.
CREATE UNIQUE INDEX IF NOT EXISTS ux_decks_user_name
    ON decks (user_id, name) WHERE deleted_at IS NULL;

-- ============================================================
-- Tags
-- ============================================================
-- Scoped to a deck, as on the desktop. Card membership lives on the card as
-- an array rather than in a join table; see below.

CREATE TABLE IF NOT EXISTS tags (
    id         uuid         PRIMARY KEY,
    user_id    uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    deck_id    uuid         NOT NULL REFERENCES decks (id) ON DELETE CASCADE,
    name       varchar(100) NOT NULL,
    position   integer      NOT NULL DEFAULT 0,
    created_at timestamptz  NOT NULL,
    updated_at timestamptz  NOT NULL,
    deleted_at timestamptz,
    server_seq bigint       NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_tags_sync ON tags (user_id, server_seq);
CREATE INDEX IF NOT EXISTS ix_tags_deck ON tags (deck_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tags_deck_name
    ON tags (deck_id, name) WHERE deleted_at IS NULL;

-- ============================================================
-- Cards
-- ============================================================

CREATE TABLE IF NOT EXISTS cards (
    id             uuid          PRIMARY KEY,
    user_id        uuid          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    deck_id        uuid          NOT NULL REFERENCES decks (id) ON DELETE CASCADE,
    front          varchar(500)  NOT NULL,
    front_type     varchar(10)   NOT NULL DEFAULT 'TEXT',
    front_language varchar(20),
    back           varchar(500)  NOT NULL,
    back_type      varchar(10)   NOT NULL DEFAULT 'TEXT',
    back_language  varchar(20),
    notes          varchar(1000),
    position       integer       NOT NULL DEFAULT 0,

    -- Tag membership as an array, not a join table. Syncing join rows means
    -- syncing relationships, which conflict in ways entities do not; here
    -- retagging is an ordinary card edit resolved by the same LWW rule.
    -- Deliberately not a foreign key: arrays cannot carry one, so a deleted
    -- tag leaves a dangling id that reads filter out.
    tag_ids        uuid[]        NOT NULL DEFAULT '{}',

    created_at     timestamptz   NOT NULL,
    updated_at     timestamptz   NOT NULL,
    deleted_at     timestamptz,
    server_seq     bigint        NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_cards_sync ON cards (user_id, server_seq);
CREATE INDEX IF NOT EXISTS ix_cards_deck ON cards (deck_id, position);

-- Lets "which cards carry this tag" stay a single indexed lookup.
CREATE INDEX IF NOT EXISTS ix_cards_tag_ids ON cards USING gin (tag_ids);

-- ============================================
-- Quizzes
-- ============================================

CREATE TABLE IF NOT EXISTS quizzes (
    id                uuid          PRIMARY KEY,
    user_id           uuid          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name              varchar(255)  NOT NULL,
    description       varchar(1000) NOT NULL DEFAULT '',
    shuffle_questions boolean       NOT NULL DEFAULT false,
    is_favorite       boolean       NOT NULL DEFAULT false,
    created_at        timestamptz   NOT NULL,
    updated_at        timestamptz   NOT NULL,
    deleted_at        timestamptz,
    server_seq        bigint        NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_quizzes_sync ON quizzes (user_id, server_seq);

CREATE UNIQUE INDEX IF NOT EXISTS ux_quizzes_user_name
    ON quizzes (user_id, name) WHERE deleted_at IS NULL;

-- Questions carry their choices inline as jsonb rather than in a child table.
-- A choice is never independently meaningful and is always edited alongside
-- its question, so inlining makes a question edit atomic and removes an entity
-- from the sync surface.
CREATE TABLE IF NOT EXISTS questions (
    id               uuid          PRIMARY KEY,
    user_id          uuid          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    quiz_id          uuid          NOT NULL REFERENCES quizzes (id) ON DELETE CASCADE,
    question_type    varchar(20)   NOT NULL,
    content          text          NOT NULL,
    content_type     varchar(10)   NOT NULL DEFAULT 'TEXT',
    content_language varchar(20),
    correct_answer   text,
    multiple_answers boolean       NOT NULL DEFAULT false,
    explanation      text,
    position         integer       NOT NULL DEFAULT 0,
    choices          jsonb         NOT NULL DEFAULT '[]',
    tag_ids          uuid[]        NOT NULL DEFAULT '{}',
    created_at       timestamptz   NOT NULL,
    updated_at       timestamptz   NOT NULL,
    deleted_at       timestamptz,
    server_seq       bigint        NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_questions_sync ON questions (user_id, server_seq);
CREATE INDEX IF NOT EXISTS ix_questions_quiz ON questions (quiz_id, position);
CREATE INDEX IF NOT EXISTS ix_questions_tag_ids ON questions USING gin (tag_ids);

-- ============================================
-- Progress
-- ============================================
-- Records of things that happened. They carry the same sync columns as
-- content, but in practice two devices never produce conflicting versions of
-- the same event, so the last-write-wins rule almost never fires here.

CREATE TABLE IF NOT EXISTS study_sessions (
    id               uuid        PRIMARY KEY,
    user_id          uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    deck_id          uuid        NOT NULL REFERENCES decks (id) ON DELETE CASCADE,
    started_at       timestamptz NOT NULL,
    ended_at         timestamptz,
    duration_seconds integer,
    cards_studied    integer     NOT NULL DEFAULT 0,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    deleted_at       timestamptz,
    server_seq       bigint      NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_study_sessions_sync ON study_sessions (user_id, server_seq);
CREATE INDEX IF NOT EXISTS ix_study_sessions_deck ON study_sessions (deck_id, started_at);

-- Per-question results are inline for the same reason as choices: they are
-- only meaningful as part of the attempt that produced them.
CREATE TABLE IF NOT EXISTS quiz_attempts (
    id               uuid        PRIMARY KEY,
    user_id          uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    quiz_id          uuid        NOT NULL REFERENCES quizzes (id) ON DELETE CASCADE,
    started_at       timestamptz NOT NULL,
    completed_at     timestamptz,
    duration_seconds integer,
    total_questions  integer     NOT NULL DEFAULT 0,
    correct_answers  integer     NOT NULL DEFAULT 0,
    score_percentage real        NOT NULL DEFAULT 0,
    question_results jsonb       NOT NULL DEFAULT '[]',
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    deleted_at       timestamptz,
    server_seq       bigint      NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_quiz_attempts_sync ON quiz_attempts (user_id, server_seq);
CREATE INDEX IF NOT EXISTS ix_quiz_attempts_quiz ON quiz_attempts (quiz_id, completed_at);
